version: "3"
services:
  #
  # Core services. These services allow a Grafana Agent to send data somewhere
  # and visualize it in Grafana.
  #
  # Backends: grafana, loki, mimir, tempo
  # Example services: avalanche
  #

  grafana:
    image: grafana/grafana:10.4.2
    environment:
      TZ: Asia/Shanghai
    entrypoint:
      - /usr/share/grafana/bin/grafana-server
      - --homepath=/usr/share/grafana
      - --config=/etc/grafana-config/grafana.ini
    volumes:
      - ./grafana/grafana_data:/var/lib/grafana
      - ./grafana/config:/etc/grafana-config
      - ./grafana/datasources:/etc/grafana/provisioning/datasources
      - ./grafana/dashboards-provisioning:/etc/grafana/provisioning/dashboards
    ports:
      - "3000:3000"
    networks:
      docker_default:
        aliases:
          - grafana-alias
networks:
  docker_default:
    external: true

